import type { SkillDefinition } from "@solara/shared";

/**
 * First skill-bar slice (spec: skill bar, keys 1-9): three real active
 * skills per class, all unlocked together once the class itself is chosen
 * at CLASS_UNLOCK_LEVEL — there's no skill-tree/skill-point spending yet
 * (`skillPointCost` is 0 and unused), see docs/gameplay/phase-status.md.
 *
 * Each skill resolves through one of three generic effects (executed by
 * TownScene): "strike" (a bigger single-target hit further out than the
 * basic attack), "nova" (an area burst centered on the player), or "heal"
 * (restores the player's own HP). Damage scales off the class's
 * `baseStats.attack` via `damageMultiplier`.
 */
export const SKILL_DEFINITIONS: SkillDefinition[] = [
  // Swordsman — energy
  {
    id: "skill-swordsman-whirlwind",
    classId: "swordsman",
    name: "Wirbelschlag",
    description: "Eine kreisende Schwertattacke, die alle Gegner in der Nähe trifft.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 20,
    cooldownMs: 4000,
    barSlot: 1,
    iconKey: "skill_swordsman_whirlwind",
    effect: "nova",
    damageMultiplier: 0.9,
    radius: 90,
  },
  {
    id: "skill-swordsman-power-strike",
    classId: "swordsman",
    name: "Kraftschlag",
    description: "Ein wuchtiger Hieb, der deutlich mehr Schaden verursacht als ein normaler Angriff.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 15,
    cooldownMs: 2500,
    barSlot: 2,
    iconKey: "skill_swordsman_power_strike",
    effect: "strike",
    damageMultiplier: 1.8,
    range: 70,
    radius: 44,
  },
  {
    id: "skill-swordsman-second-wind",
    classId: "swordsman",
    name: "Kampfrausch",
    description: "Kurzer Kampfrausch, der einen Teil deiner Lebenspunkte wiederherstellt.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 35,
    cooldownMs: 12000,
    barSlot: 3,
    iconKey: "skill_swordsman_second_wind",
    effect: "heal",
    healAmount: 35,
  },

  // Tank — energy
  {
    id: "skill-tank-shield-bash",
    classId: "tank",
    name: "Schildschlag",
    description: "Ein Schildstoß mit hohem Einzelschaden.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 15,
    cooldownMs: 2500,
    barSlot: 1,
    iconKey: "skill_tank_shield_bash",
    effect: "strike",
    damageMultiplier: 1.6,
    range: 60,
    radius: 44,
  },
  {
    id: "skill-tank-bulwark",
    classId: "tank",
    name: "Bollwerk",
    description: "Eine Schockwelle, die alle Gegner in der Nähe zurückschlägt.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 20,
    cooldownMs: 5000,
    barSlot: 2,
    iconKey: "skill_tank_bulwark",
    effect: "nova",
    damageMultiplier: 0.7,
    radius: 100,
  },
  {
    id: "skill-tank-fortify",
    classId: "tank",
    name: "Wiederherstellung",
    description: "Verstärkte Rüstung stellt einen großen Teil deiner Lebenspunkte wieder her.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 30,
    cooldownMs: 10000,
    barSlot: 3,
    iconKey: "skill_tank_fortify",
    effect: "heal",
    healAmount: 45,
  },

  // Mage — mana
  {
    id: "skill-mage-fireball",
    classId: "mage",
    name: "Feuerball",
    description: "Ein Feuerball, der auf große Entfernung hohen Schaden verursacht.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 25,
    cooldownMs: 3000,
    barSlot: 1,
    iconKey: "skill_mage_fireball",
    effect: "strike",
    damageMultiplier: 1.7,
    range: 130,
    radius: 46,
  },
  {
    id: "skill-mage-frost-nova",
    classId: "mage",
    name: "Frostnova",
    description: "Eine Eisexplosion, die alle Gegner um dich herum trifft.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 30,
    cooldownMs: 4500,
    barSlot: 2,
    iconKey: "skill_mage_frost_nova",
    effect: "nova",
    damageMultiplier: 1.0,
    radius: 95,
  },
  {
    id: "skill-mage-arcane-renewal",
    classId: "mage",
    name: "Arkane Genesung",
    description: "Arkane Energie heilt einen Teil deiner Lebenspunkte.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 40,
    cooldownMs: 11000,
    barSlot: 3,
    iconKey: "skill_mage_arcane_renewal",
    effect: "heal",
    healAmount: 30,
  },

  // Archer — energy
  {
    id: "skill-archer-power-shot",
    classId: "archer",
    name: "Präzisionsschuss",
    description: "Ein gezielter Schuss mit hoher Reichweite und hohem Schaden.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 18,
    cooldownMs: 2800,
    barSlot: 1,
    iconKey: "skill_archer_power_shot",
    effect: "strike",
    damageMultiplier: 1.7,
    range: 150,
    radius: 40,
  },
  {
    id: "skill-archer-volley",
    classId: "archer",
    name: "Mehrfachschuss",
    description: "Ein Pfeilhagel, der alle Gegner in der Nähe trifft.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 24,
    cooldownMs: 4200,
    barSlot: 2,
    iconKey: "skill_archer_volley",
    effect: "nova",
    damageMultiplier: 0.8,
    radius: 120,
  },
  {
    id: "skill-archer-adrenaline",
    classId: "archer",
    name: "Adrenalin",
    description: "Ein Adrenalinschub heilt einen Teil deiner Lebenspunkte.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 32,
    cooldownMs: 10000,
    barSlot: 3,
    iconKey: "skill_archer_adrenaline",
    effect: "heal",
    healAmount: 30,
  },

  // Assassin — energy
  {
    id: "skill-assassin-shadow-strike",
    classId: "assassin",
    name: "Schattenklinge",
    description: "Ein blitzschneller Dolchstoß mit sehr hohem Schaden.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 16,
    cooldownMs: 2200,
    barSlot: 1,
    iconKey: "skill_assassin_shadow_strike",
    effect: "strike",
    damageMultiplier: 2.0,
    range: 65,
    radius: 42,
  },
  {
    id: "skill-assassin-venom-cloud",
    classId: "assassin",
    name: "Giftwolke",
    description: "Eine Giftwolke, die alle Gegner in der Nähe vergiftet.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 22,
    cooldownMs: 4800,
    barSlot: 2,
    iconKey: "skill_assassin_venom_cloud",
    effect: "nova",
    damageMultiplier: 0.75,
    radius: 100,
  },
  {
    id: "skill-assassin-blood-rush",
    classId: "assassin",
    name: "Blutrausch",
    description: "Blutrausch heilt einen Teil deiner Lebenspunkte.",
    type: "active",
    branch: "core",
    levelRequirement: 5,
    skillPointCost: 0,
    resourceCost: 28,
    cooldownMs: 10000,
    barSlot: 3,
    iconKey: "skill_assassin_blood_rush",
    effect: "heal",
    healAmount: 28,
  },
];

export function getSkillsForClass(classId: string): SkillDefinition[] {
  return SKILL_DEFINITIONS.filter((s) => s.classId === classId).sort((a, b) => a.barSlot - b.barSlot);
}
